### ISSUE TITLE
[REQ] Add Task Failed when Achieving Max Number

### ISSUE THREAD

**Issue by poor1017** [bshoshany/thread-pool#101]
**Describe the new feature**
I have a web server using `BS_thread_pool` as process pool, and I want to limit the call of the server, so I set the pool size as `MAX_SIZE`. When the call number exceed the pool size, we cannot add the task to the pool. I do not find this feature in `BS_thread_pool`.

**Code example**
```cpp
BS::thread_pool pool(2);
bool ret = false;
ret = pool.add_task_for_run(task1); // ret is true
ret = pool.add_task_for_run(task2); // ret is true
ret = pool.add_task_for_run(task3); // ret is false
```

**Additional information**
I may call `add_task_for_run` in different threads.

**Comment by poor1017** [comment]
I know I can use:
```cpp
size_t num_running_tasks = pool.get_tasks_running();
if (num_running_tasks > 2) {
    // Refuse.
} else {
    pool.push_task(task);
}
```
But I need add lock for thread safe.
Can we support this feature as built-in?

Thank you!

**Comment by poor1017** [comment]
I implement it by myself. Here is my code:
```cpp
/**
 * @brief Run a function with zero or more arguments, but no return value, into the task queue. Does not return a future, so the user must use wait_for_tasks() or some other method to ensure that the task finishes executing, otherwise bad things will happen.
 *
 * @tparam F The type of the function.
 * @tparam A The types of the arguments.
 * @param task The function to push.
 * @param args The zero or more arguments to pass to the function. Note that if the task is a class member function, the first argument must be a pointer to the object, i.e. &object (or this), followed by the actual arguments.
 * @return true if the pool has valid thread, false if it has not.
 */
template <typename F, typename... A>
bool run_task(F&& task, A&&... args)
{
    std::function<void()> task_function = std::bind(std::forward<F>(task), std::forward<A>(args)...);
    {
        const std::scoped_lock tasks_lock(tasks_mutex);
        if (tasks_total < thread_count) {
            tasks.push(task_function);
        } else {
            return false;
        }
    }
    ++tasks_total;
    task_available_cv.notify_one();

    return true;
}
```
I am not sure whether there is a better way.

Thank you!

**Comment by v1993** [comment]
That function looks good. The only change I'd do is rename function to `try_push_task` and edit comment to actually explain the difference.

**Comment by bshoshany** [comment]
Thanks for opening this issue. However, I don't think this change makes sense. The whole idea of the thread pool is that you have a set of N threads and an **unlimited** queue of tasks. A new task is automatically taken from the queue every time a thread becomes free, and executed on that free thread. Your code appears to only allow putting a task in the queue when the queue has less than N tasks, which makes no sense and gives no performance advantage. If there are 100 tasks in the queue, this doesn't mean all 100 tasks will run at the same time, they will be run one by one as the threads become available.

**Comment by OrenHg** [comment]
maybe he should do it like this:

`/**
 * @brief Run a function with zero or more arguments, but no return value, into the task queue. Does not return a future, so the user must use wait_for_tasks() or some other method to ensure that the task finishes executing, otherwise bad things will happen.
 *
 * @tparam max The max number of tasks supposed to be in queue
 * @tparam F The type of the function.
 * @tparam A The types of the arguments.
 * @param task The function to push.
 * @param args The zero or more arguments to pass to the function. Note that if the task is a class member function, the first argument must be a pointer to the object, i.e. &object (or this), followed by the actual arguments.
 * @return true if the pool has valid thread, false if it has not.
 */
template <typename F, typename... A>
bool run_task(unsigned int max, F&& task, A&&... args)
{
    std::function<void()> task_function = std::bind(std::forward<F>(task), std::forward<A>(args)...);
    {
        const std::scoped_lock tasks_lock(tasks_mutex);
        if (tasks_total < max) {
            tasks.push(task_function);
        } else {
            return false;
        }
    }
    ++tasks_total;
    task_available_cv.notify_one();

    return true;
}`
