### ISSUE TITLE
[REQ] Improving API for parallelizing loops

### ISSUE THREAD

**Issue by artem-ogre** [bshoshany/thread-pool#102]
Thank you, Barak, for this library. It is very simple and easy to use. :heart_eyes: 

However, I feel that there is a missed opportunity to have a simpler and more intuitive API for `parallelize_loop`.
Suggestion I have is to pass a range and an __operation on an element of the range__ instead a of a partial loop function.

To give an example. Here's how it is currently done:
```cpp
auto loop = [](const T a, const T b)
{
    for (T i = a; i < b; ++i)
        do_something(i);
};
BS::multi_future<void> loop_future = pool.parallelize_loop(start, end, loop, num_blocks);
loop_future.wait();
```
Suggested API:
```cpp
auto iteration = [](const T i)
{
    do_something(i);
};
BS::multi_future<void> loop_future = pool.parallelize_loop(start, end, iteration, num_blocks);
loop_future.wait();
```
This can be achieved internally by  wrapping the iteration into a loop lambda, here's some pseudocode to give an idea:
```cpp
const auto block_loop = [&iteration, block]
{
    for (auto i = block.first; i != block.last; ++i)
    {
        iteration(i);
    }
});
```
In addition to having simpler client code, passing an operation instead of a loop is subjectively more idiomatic (e.g., similar to how it's done in std library). What do you think?

**P.S.**
I also needed to pass the block index into the iteration, so I implemented another flavor of the above that looks like this:
```cpp
const auto block_loop = [&iteration, block, i_block]
{
    for (auto i = block.first; i != block.last; ++i)
    {
        iteration(i, i_block);
    }
});
```
Could this also be something worth considering in `thread_pool`?

**Comment by bshoshany** [comment]
Hi @artem-ogre and thanks for opening this issue! I'm glad you like my library! :)

I actually had something similar to this in early draft versions, but I found in my tests that it provided poor performance.

I believe the issue is that function calls take time. Consider for example a loop from 1 to 1000, split into 10 blocks. The way it works right now, there are only 10 function calls, 1 per block. However, if the function `iteration(i)` was called individually for each `i`, then I would have 1000 function calls, which would be considerably slower.

Therefore, purely for performance reasons, I think it's best to leave the API as it is. However, if you can show that your method works faster (or at least as fast) for some realistic cases, then I may incorporate it as a separate member function.

Thanks again for the suggestion!
