### ISSUE TITLE
Question about parallelize_loop

### ISSUE THREAD

**Issue by BenjaminChi007** [bshoshany/thread-pool#11]
Does "while (blocks_running != 0) in for loop scope" make block push_task not run parallelized? Thanks
![image](https://user-images.githubusercontent.com/33932393/120458827-32525a00-c3ca-11eb-909f-cf8c465d899f.png)

**Comment by bshoshany** [comment]
Yes, you are correct.

I copied this function from another library I wrote, where a similar function is used to parallelize matrix operations. I must have made a mistake when adapting the function to parallelize one loop instead of two. Since I did the benchmarks using the matrix parallelizer instead of the loop parallelizer, I never noticed this issue.

I will post a new release where this is corrected in a bit. Thank you so much for spotting this!
