### ISSUE TITLE
rvalue parameters

### ISSUE THREAD

**Issue by amin63moradi** [bshoshany/thread-pool#13]
Hi and thanks.
How to send a unique_ptr as a parameter of task?

**Comment by bshoshany** [comment]
Can you provide a minimal working example of the issue?

**Comment by amin63moradi** [comment]
`

    thread_pool tPool(1);
    unique_ptr<int> uptr = make_unique<int>(2);
    //std::cout << *(uptr.get());
    tPool.push_task([uptr = move(uptr)]() {
        std::cout << *(uptr.get());
    });

`

**Comment by bshoshany** [comment]
The easiest solution would be to simply use `std::shared_ptr` instead of `std::unique_ptr`. So I guess the question is why the pointer has to be unique in the first place. You can get it to work using two nested lambdas, but I'm not sure this is exactly what you want:

```cpp
#include "thread_pool.hpp"

int main()
{
    thread_pool pool;
    std::unique_ptr<int> uptr = std::make_unique<int>(2);
    auto print_ptr = [uptr = std::move(uptr)] { std::cout << *(uptr.get()) << '\n'; };
    auto f = pool.submit([&print_ptr] { print_ptr(); });
    f.wait();
}
```

(The reason I used a future here is that the objects will all be destructed when reaching the closing bracket of the `main` function, but the task will most likely only execute after that, so waiting for the task to complete first prevents a segmentation fault.)

**Comment by amin63moradi** [comment]
Hello
I have to use _unique_ptr_ it in my program (the output of another class)
I can not use your suggested method either because I can not use the future(The main thread  not waiting)

**Comment by bshoshany** [comment]
You don't need the future for this to work, I only used it in this particular example because otherwise there would be a segmentation fault when the main function ends. Just replace `submit` with `push_task` and it will still work.

**Comment by amin63moradi** [comment]
i replaced, but when main thread exited from particular function, i get segmentation fault

    thread_pool tPool(1);
    void TestFun()
    {
        unique_ptr<int> uptr = make_unique<int>(2);
        auto print_ptr = [uptr = std::move(uptr)] {
            this_thread::sleep_for(chrono::seconds(2));
            qDebug() << *(uptr.get()) << '\n';
        };
        tPool.push_task([&print_ptr] { print_ptr(); });
     }
    int main()
    {
       TestFun();
    }

even if you pass uptr to TestFunc, you will get invalid results


      thread_pool tPool(1);
      void TestFun( unique_ptr<int> uptr )
      {
      
          auto print_ptr = [uptr = std::move(uptr)] {
              this_thread::sleep_for(chrono::seconds(2));
              qDebug() << *(uptr.get()) << '\n';
          };
          tPool.push_task([&print_ptr] { print_ptr(); });
      }
      
      int main()
      {
          unique_ptr<int> uptr = make_unique<int>(2);
          TestFun(move(uptr));
      }

**Comment by bshoshany** [comment]
First of all, instead of using `this_thread::sleep_for()`, I recommend using a future like I did above. You can return the future from `TestFun()` and then use `wait()` in the last line of `main()`. The segfault you get is due to the `main` function exiting before the task had a chance to run, but it's unnecessary to wait for an arbitrary amount of time as you did - that's exactly what futures are for! In any case, this won't solve your problem, it's just general advice for how to use the thread pool.

After experimenting with your code for a bit, I believe the reason it doesn't work is that `move` doesn't actually do what it's supposed to do, and the `unique_ptr` gets destructed when the function `TestFun()` finishes, resulting in garbage values being read from memory when the task gets executed.

I'm guessing the reason might be that `push_task` stores the function `print_ptr` as an `std::function<void()>` in the thread pool's task queue, but the latter requires the function to be `CopyConstructible`, while `unique_ptr` is `MoveConstructible`. Perhaps if I use a more generic function type in the queue it will solve the problem - that is something that's already on my TODO list, but it might take some time until I get around to implementing it.

The solution, however, is very simple, as I already suggested above: use `shared_ptr` instead of  `unique_ptr`. You said above that another class outputs a `unique_ptr`, but you can easily convert that into a `shared_ptr`! Here is an example, which works perfectly:

```cpp
#include "thread_pool.hpp"

thread_pool pool;

auto return_unique()
{
    return std::make_unique<int>(2);
}

auto test()
{
    // Unique pointer received from somewhere else
    std::unique_ptr<int> uptr = return_unique();
    // Convert it to shared pointer
    std::shared_ptr<int> sptr = std::move(uptr);
    return pool.submit([sptr]
                       { std::cout << *sptr << '\n'; });
}

int main()
{
    auto f = test();
    f.wait();
}
```

If you don't like shared pointers, you can even just use a raw pointer:

```cpp
auto test()
{
    // Unique pointer received from somewhere else
    std::unique_ptr<int> uptr = return_unique();
    // Convert it to a raw pointer
    int *ptr = uptr.release();
    return pool.submit([ptr]
                       { std::cout << *ptr << '\n'; });
}
```

Hope this helps.

**Comment by bshoshany** [comment]
First of all, instead of using `this_thread::sleep_for()`, I recommend using a future like I did above. You can return the future from `TestFun()` and then use `wait()` in the last line of `main()`. The segfault you get is due to the `main` function exiting before the task had a chance to run, but it's unnecessary to wait for an arbitrary amount of time as you did - that's exactly what futures are for! In any case, this won't solve your problem, it's just general advice for how to use the thread pool.

After experimenting with your code for a bit, I believe the reason it doesn't work is that `move` doesn't actually do what it's supposed to do, and the `unique_ptr` gets destructed when the function `TestFun()` finishes, resulting in garbage values being read from memory when the task gets executed.

I'm guessing the reason might be that `push_task` stores the function `print_ptr` as an `std::function<void()>` in the thread pool's task queue, but the latter requires the function to be `CopyConstructible`, while `unique_ptr` is `MoveConstructible`. Perhaps if I use a more generic function type in the queue it will solve the problem - that is something that's already on my TODO list, but it might take some time until I get around to implementing it.

The solution, however, is very simple, as I already suggested above: use `shared_ptr` instead of  `unique_ptr`. You said above that another class outputs a `unique_ptr`, but you can easily convert that into a `shared_ptr`! Here is an example, which works perfectly:

```cpp
#include "thread_pool.hpp"

thread_pool pool;

auto return_unique()
{
    return std::make_unique<int>(2);
}

auto test()
{
    // Unique pointer received from somewhere else
    std::unique_ptr<int> uptr = return_unique();
    // Convert it to shared pointer
    std::shared_ptr<int> sptr = std::move(uptr);
    return pool.submit([sptr]
                       { std::cout << *sptr << '\n'; });
}

int main()
{
    auto f = test();
    f.wait();
}
```

If you don't like shared pointers, you can even just use a raw pointer (but I wouldn't recommend it, due to the possibility of memory leaks if not done correctly):

```cpp
auto test()
{
    // Unique pointer received from somewhere else
    std::unique_ptr<int> uptr = return_unique();
    // Convert it to a raw pointer
    int *ptr = uptr.release();
    return pool.submit([ptr]
                       {
                           std::cout << *ptr << '\n';
                           // Don't forget to deallocate the memory!
                           delete ptr;
                       });
}
```

Hope this helps.

**Comment by amin63moradi** [comment]
I wrote this code just to show the problem and I know the uses of the future.
I wanted to use your _thread_pool_ in a complex code that has several _object-pool_ which objects are passed between them and it is hard to use raw pointers in them  (And convert  _shared_ptr_ to _unique_ptr_ is impasible or dangerous)  
Thanks anyway

**Comment by bshoshany** [comment]
I see. Sorry I couldn't help you! I'll look into replacing the function wrapper in the task queue, which - as I mentioned above - may solve the problem, but it might take me a few weeks to get to it. I'll keep you posted.

**Comment by joaovitor72** [comment]
I use a custom version of thread-pool where i substituted std::function<void()> for fu2::unique_function<void()> from the Naios/function2. There are also other drop-in replacements for the std::function that support non copyable objects.

fu2::unique_function is very similar to the std::function, but does not offer the copy methods. The only tricky part to change from std::function to the fu2::unique_function is that you kinda need c++20 for perfect capture in lambdas with parameter pack arguments or else you need to use some not so pretty hacks.

**Comment by bshoshany** [comment]
Thanks for the input @joaovitor72!

My philosophy is that the thread pool class should be as lightweight as possible (Naios/function2 is 1792 lines, i.e. 3.3 times longer than the entire thread pool!) and 100% self-contained, so I always prefer to write things from scratch rather than use other packages - with the exception of the standard library, of course.
 
This issue is currently not high priority for me because 1. it seems to me that the OP's situation is not something most users will run into, and 2. I'm not sure a robust solution is even possible with using questionable hacks, as you mentioned.

That said, I do have it on my TODO list and I hope to get to it eventually, but meanwhile I think I'll close this issue, since I do not see it as a significant issue with the thread pool library itself.
