### ISSUE TITLE
[REQ] ability to set threads to 0, and have everything execute serially

### ISSUE THREAD

**Issue by wkjarosz** [bshoshany/thread-pool#141]
This looks like a great library, and I'm considering using it. However, I'd like my application to optionally work without any additional threads being created (for instance, if I want to avoid using pthreads when compiling my code with emscripten for the web).

I would love to use your library, but currently I'd have to manually write separate code for the single-threaded version. Instead, I'd like to submit tasks, loops, etc, but if the number of threads in the threadpool is set to 0 (or some compile-time macro is set) no worker threads should ever be created, and everything should just execute in serial. 

As an example, the [openexr library](https://github.com/AcademySoftwareFoundation/openexr) allows setting the number of worker threads to 0 (or compiling with threading disabled), and in that case everything runs in a main thread, even though the code is written in terms of a threadpool and tasks.

Is this something you would consider?

**Comment by bshoshany** [comment]
Hi @wkjarosz and thanks for making this suggestion! I think this can be implemented, but I need a bit more information, since unfortunately I don't have much experience with Emscripten. When you say you want to avoid using pthreads, do you mean that Emscripten does not support the C++11 Standard Library `<thread>` header (or related headers such as `<future>`, `<mutex>`, etc.) at all? If so, then I imagine just setting the number of threads to 0 would not be enough, since that's a runtime value; it would have to be a macro that completely turns off anything in the thread support library at compilation time and just runs everything in kind of a single-threaded "simulation" of multi-threading.

**Comment by wkjarosz** [comment]
Including `<thread>`, `<future>`, `<mutex>` should be fine for my use case -- this would all work fine with emscripten; but it would nonetheless be nice to guarantee that no threads are ever launched and all work happens in the calling thread (e.g. when calling `.get()` on the `future`; much like when using `std::async` with policy `std::launch::deferred`).

Background: pthreads do work with emscripten, but it can also make the resulting web app much more heavy weight, particularly if the amount of memory usage is not known in advance; so i'd like the option of building the web app without threading enabled.
