### ISSUE TITLE
Get rid of shared pointer for submitted tasks promises

### ISSUE THREAD

**Issue by NewbiZ** [bshoshany/thread-pool#145]
**Describe the new feature**

I have noticed that submitted tasks carry their promises using a captured `shared_ptr`. That seems overweight to me, as the promises should semantically just travel from the main thread, to the queue, to the worker thread. C++14 introduced the possibility to move promises (and lambda move captures), which I think is what should be used here to avoid the creation of a heavyweight `shared_ptr`.

**Comment by bshoshany** [comment]
Hi @NewbiZ and thanks for opening this issue! I tried getting read of the `shared_ptr` in the past, but the problem is that while the lambda can move-capture the promise, that makes the lambda non-copyable, and therefore you cannot create an `std::function` out of it in order to store it in the task queue.

This can be solved in C++23 with `std::move_only_function`, but since this is a C++17 library (for now), I can't use that.

If you can figure out how to make it work in C++17, and the test program compiles successfully with your new code, please post your solution here!
