### ISSUE TITLE
Use semaphores instead of sleeping

### ISSUE THREAD

**Issue by tommitytom** [bshoshany/thread-pool#15]
Have you considered using a semaphore to wait for available tasks instead of using a sleep?  I'm not sure if it's a better method, more interested in your opinion on the matter more than anything!  Lightweight semaphore here: https://github.com/preshing/cpp11-on-multicore/blob/master/common/sema.h

This article is interesting, particularly point 2: https://preshing.com/20150316/semaphores-are-surprisingly-versatile/

**Comment by bshoshany** [comment]
Thanks for the suggestion! This has actually been on my TODO list for a while, and I think it may improve performance, but that remains to be seen. However, I don't want to use a 3rd-party implementation, since I want my code to be maximally portable. Therefore, I was planning to use `std::counting_semaphore` from the C++20 standard library and posting the code as a separate C++20 thread pool library (tentatively named `thread_pool20.hpp`). Unfortunately I'm very busy with other stuff right now, so I expect it to be a month or two before I get to it.

**Comment by tommitytom** [comment]
Oh lovely, I had no idea C++20 had a portable semaphore.  About time though eh? Hah. Look forward to the update :)

**Comment by bshoshany** [comment]
This is still on my TODO list, but not high priority unfortunately. I've decided to close this issue now, because if I do implement the thread pool using C++20 semaphores I will most likely publish the code in a separate repository in any case.

**Comment by fwsGonzo** [comment]
I'm getting abysmal performance compared to https://github.com/progschj/ThreadPool

The overhead of activating the threadpool is extremely high compared to simple condition waiting.
progschj/ThreadPool:
```
> median 11004ns  		lowest: 10454ns     	highest: 13736ns
>>> Measurement "Multi-processing overhead" median: 11004 nanos

> median 93446ns  		lowest: 75931ns     	highest: 120575ns
>>> Measurement "Multi-processing dotprod" median: 93446 nanos
```
There is a 10 microsecond overhead (which I personally think is way too much).

This threadpool:
```
> median 39186ns  		lowest: 35673ns     	highest: 45017ns
>>> Measurement "Multi-processing overhead" median: 39186 nanos

> median 156754ns  		lowest: 151290ns     	highest: 161348ns
>>> Measurement "Multi-processing dotprod" median: 156754 nanos
```
This is with 1 microsecond "sleep". The overhead is 39 microseconds to activate it.

**Comment by bshoshany** [comment]
Thanks for the information! The performance will be greatly improved in v3.0.0, which will eliminate sleep in favor of condition variables and/or semaphores. I would appreciate if you could repeat this test once the new version is released, in a month or two.

I also note that the thread pool you linked here is extremely simplistic and has no features other than submitting tasks to the pool, so it may be faster due to the fact that it contains much less code...

**Comment by bshoshany** [comment]
Update: In v3.0.0, to be released in the next few days, the thread pool has been updated to use `std::condition_variable`. A C++20 version using semaphores will be added later.

**Comment by EduardoGRocha** [comment]
@bshoshany has the C++20 version been released? It would be great if threads would do some sort of busy waiting/spinning before being put to sleep (configurable). 

My application alternates between large parallel chunks and an (oftentimes) very small single-threaded section such that putting the threads to sleep add too much overhead

**Comment by bshoshany** [comment]
Hi @EduardoGRocha! This issue is more than 4 years old. The thread pool currently uses C++20 and even C++23 features when available. Threads never sleep, they use `std::condition_variable` (or `std::condition_variable_any` in C++20/23) to wait for tasks, which results in extremely high performance. Rest assured that you can safely use this library in your app.
