### ISSUE TITLE
Use  lock-free queue as the task queue

### ISSUE THREAD

**Issue by renzibei** [bshoshany/thread-pool#25]
In the current code, a normal queue with mutex lock is used as the task queue. The cost of lock cannot be ignored when there are a lot of small tasks. The overheads cause that the sleep duration of per worker cannot be too short or even use busy-polling. I think a lock-free queue could help solve this problem. 
The [CTPL](https://github.com/vit-vit/CTPL) project also uses a version using lock-free queue to improve the performance.

**Comment by bshoshany** [comment]
Hi @renzibei and thanks for the suggestion! :)

One of the main design philosophies behind this thread pool library is that it should be as light, portable, and self-contained as possible. I want it to be just one header file that will work on any platform that has a C++17-compliant compiler. Therefore, I limit myself to using only standard C++17, with no external dependencies such as Boost. I am aware that a lock-free queue could improve the performance of this library, but I don't want that to be at the cost of the lightness and portability of the library.

I'm working on a version that uses condition variables instead of sleep, and planing a C++20 version that will use semaphores, both of which should improve the performance. I will also take a look at how Boost implements the lock-free queue and see if I can perhaps implement something similar in my library. All of this will probably take at least a month or two though since I'm really busy these days with teaching and grant applications.

**Comment by bshoshany** [comment]
Update: v3.0.0, to be released in the next few days, will modify the thread pool to use `std::condition_variable`, which substantially improves performance. Looking into lock-free queues is still on my TODO list for a future release.
