### ISSUE TITLE
Memory usage?

### ISSUE THREAD

**Issue by WindowsNT** [bshoshany/thread-pool#34]
It seems nice, I noticed the use of std::shared_ptr. Can it avoid calls to memory allocations?

**Comment by bshoshany** [comment]
Thanks for the comment. In the initial version I used `std::packaged_task`, but I found that `std::shared_ptr` actually provides better performance. However, I'm currently working on a new version (v3.0.0) that is essentially going to be rewritten from scratch, and in that version I am going to try `std::packaged_task` again and see if it works better.

**Comment by bshoshany** [comment]
Update: After reviewing past issues I realized that in #26 it was mentioned that using `std::packaged_task` makes the library incompatible with MSVC. Therefore, I have decided to keep using `std::shared_ptr` in `submit()` for the time being. However, I did slightly modify the code to use `std::make_shared` for creating the shared pointer, which [only performs one allocation instead of two](https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared), and therefore should increase performance.
