### ISSUE TITLE
Compiling on Amazon Linux

### ISSUE THREAD

**Issue by danchitnis** [bshoshany/thread-pool#46]
**Describe the bug**

I am trying to compile my code which uses your thread_pool library. The code compiles and runs without any problems on my own PC (WSL2 and GCC). When I compile on Amazon Linux 2, I get the errors attached in the file, during compile time. The code and compile commands are exactly the same. Since your library is based on C++17, I wonder why there is a compile error. Any suggestions for the reasons for the errors?

**Minimal working example**

not yet.

**Behavior**

[errors.txt](https://github.com/bshoshany/thread-pool/files/8820733/errors.txt)

**System information**

* CPU model, architecture, # of cores and threads: AWS EC2 t2.micro
* Operating system: Amazon Linux 2
* Name and version of C++ compiler: GCC
* Full command used for compiling, including all compiler flags: -std=c++17 -march=native -O3 -pthread
* Thread pool library version: 3.0.0

**Additional information**

same compile errors between versions 2 and 3.

**Comment by AlexanderSerov** [comment]
Check [this](https://github.com/bshoshany/thread-pool/issues/39)

**Comment by bshoshany** [comment]
Hi @danchitnis, thanks for opening this issue. I'm not really sure why you're getting these errors. Since you're saying the exact same code did compile on a different system, my guess is that this is most likely due to either a corrupted compiler installation or an old compiler version that doesn't fully support C++17.

* Which version of GCC are you using? Is it the same version on both systems?
* Can you try compiling this on Amazon Linux with a different compiler, such as Clang?
* Can you attach the file `klu_threaded.cpp` that you're trying to compile so I can test it myself?

**Comment by danchitnis** [comment]
@bshoshany I also suspect it is an old version of GCC which doesn't fully support C++17. This is quite ironic because then compiling with `-march=native` wouldn't make sense if the CPU is newer than gcc. I will do some testing in docker on my PC and get back to you.
PS: well done for developing this library, just realised you are an academic too 😉

**Comment by bshoshany** [comment]
@danchitnis sounds good, please let me know. Meanwhile I am closing this issue as I do not believe it is an issue with the package itself.

Thanks, I'm glad you like the library. If you use it in academic research, please don't forget to cite the paper 😊

**Comment by danchitnis** [comment]
It turns out that Amazon Linux has a GCC version 7 as default. So I recommend anyone who wants to use this library on AWS EC2, to use Ubuntu 22.04 and install GCC version 10 via: 

```bash
sudo apt update
sudo apt install build-essential
```

Then the compilation is successful.

**Comment by bshoshany** [comment]
Glad it worked out!
