### ISSUE TITLE
[Question] How to remove a queued thread not running

### ISSUE THREAD

**Issue by Nelson-numerical-software** [bshoshany/thread-pool#57]
Assume 4 threads running and 4 other threads queuing.
To stop the execution of one running thread, it is possible to define a variable in the execution function.
But how to remove/cancel a queued thread which is not yet running.

my current workaround is to wait that thread comes running and to stop/cancel.
Any others better way will be appreciate :)

**Comment by haciMMicah** [comment]
I just came across this repo, but I have implemented this type of functionality before. The main challenge is being able to have fine-grained control over signaling threads to wake up.

My approach was to map a monotonically increasing task_id to a thread id using an unordered_map. Then also map a separate condition_variable per thread in order to wake specific threads from their condition_variable wait. This approach also requires that you increase the execution time for signaling all of the condition_variables for each thread rather than just calling notify_all on a single condition_variable. You can then implement functionality to signal any thread including non currently executing threads. Note that you would still use the same task queue mutex in each condition_variable. It worked moderately well, like I said there was a tradeoff with the execution time for actually signaling all of the condition variables that there was a task in the queue.

Alternatively you could used timed waits in your condition_variables and busy-wait check the condition to cancel that thread's execution. This approach works but is pretty inefficient as it wastes a lot of cpu-cycles.

**Comment by bshoshany** [comment]
@Nelson-numerical-software, here's my suggestion: assign each task you submit a boolean value stored somewhere in memory (e.g. inside a vector). Then set up the task's code so that it first checks the corresponding boolean value, and only executes if it is set to `true`. That way, if you want to cancel a particular task, you just need to set its corresponding value to `false`.
