### ISSUE TITLE
Compile error c2064

### ISSUE THREAD

**Issue by tuandat64** [bshoshany/thread-pool#7]
Hi, I got an error c2064 when merging your file with my program.
void IndicatorDRSI::Refresh(const int limit, const  int newBars, const  int startbar)
{
	doubleRsiLine->RefeshDRsi( my_symbol, limit, newBars, startbar);
}
void IndicatorDRSI::RefreshRate(const int limit, const int newBars, const int startbar)
{
	auto x = &IndicatorDRSI::Refresh;
	thread_pool pool(12);
	pool.push_task(x, limit, newBars, startbar);
}

Error C2064 term does not evaluate to a function taking 3 arguments	doubleRsi line 154
Here line 154
  template <typename F, typename... A>
    void push_task(const F& task, const A &...args)
    {
        push_task([task, args...]
            { task(args...); });// line 154
    }	
I use Microsoft Visual Studio Community 2019. Version 16.9.4

Please help me, 
Thank you very much
Jewel

**Comment by bshoshany** [comment]
First of all, you shouldn't create the thread pool inside a function, because it gets destructed as soon as the function block ends. The whole point of a thread pool is that you create it once, and then use the same pool everywhere in the code. This may not be the source of this specific error, but it's something you should fix ASAP.

Second, please provide a **minimal working example**, i.e. the smallest possible C++ source file that can be compiled and that produces this error, so that I can try it on my end.

**Comment by tuandat64** [comment]
Thank you for the quick reply

Here you are
[doubleRsi.zip](https://github.com/bshoshany/thread-pool/files/6425406/doubleRsi.zip)

**Comment by bshoshany** [comment]
The problem here is that you're trying to use a member function as the queued task, but a member function is meaningless without an object to invoke it on. [See discussion here.](https://isocpp.org/wiki/faq/pointers-to-members)

One solution could be to wrap the member function inside a lambda, e.g.:

```cpp
mainPool->push_task([=] { IndicatorDRSI::Refresh(limit, newBars, startbar); });
```

In any case, I'm closing this issue since it's not an issue with the thread pool itself, but rather a general concept in C++.
