### ISSUE TITLE
Parallel loop example should maybe warn about false-sharing ?

### ISSUE THREAD

**Issue by ddevienne** [bshoshany/thread-pool#86]
In https://github.com/bshoshany/thread-pool#parallelizing-loops-without-futures the loop breaks a 100 int array into 10 chunks of 10 ints, but cache lines are typically 64-bytes thus 8-ints longs. This means the threads will have false-sharing at the _boundaries_, decreasing performance, right? I'm no expert though, of course. Maybe just a mention in the doc about false-sharing and/or in case anyone does a naive _reduction_ across threads w/o synchronization might be useful in that part of the doc, no?

**Comment by bshoshany** [comment]
Thanks for opening this issue @ddevienne! This is just a trivial example, meant to illustrate how to use the `push_loop()` member function. In this particular case there is no actual benefit to the parallelization anyway, since the calculation is so trivial, so false sharing is not relevant. The purpose of the documentation is only to teach the basics of how to use this library, not to teach how to do multithreading in general, which is beyond the scope of the documentation and requires plenty of background knowledge that the average reader does not have.
