### ISSUE TITLE
[BUG] push_loop tries to move a previously moved lambda

### ISSUE THREAD

**Issue by sethhillbrand** [bshoshany/thread-pool#88]
**Describe the bug**

`push_loop` tries to move a previously moved rvalue.  In the case where `F&& loop` is an rvalue (e.g. when using a lambda), `std::forward` will call `std::move` on the loop each time the loop is passed to `push_task`.

**Minimal working example**

```cpp
#include <vector>
#include "BS_thread_pool.hpp"
BS::thread_pool pool(2);

int main()
{
    std::vector<int> values(500);

    pool.push_loop( values.size(), [&]( const size_t a, const size_t b ) 
    {
        for( size_t ii = a; ii < b; ++ii )
            values[ii] = ii;
    }
    );

    pool.wait_for_tasks();

    for( auto ii : values )
        std::cout << ii << " ";
    
    std::cout << std::endl;
}
```

**Behavior**

The example will compile and run on both clang and gcc.  However, calling std::move on an already moved object means that it is placed in a "valid but unspecified state." (http://eel.is/c++draft/lib.types.movedfrom)

This may not cause any problems but that might also be compiler-dependent 

**Suggested Resolution**

```
diff --git a/BS_thread_pool.hpp b/BS_thread_pool.hpp
index 840bcdc..af3a06f 100644
--- a/BS_thread_pool.hpp
+++ b/BS_thread_pool.hpp
@@ -393,8 +393,9 @@ public:
         blocks blks(first_index, index_after_last, num_blocks ? num_blocks : thread_count);
         if (blks.get_total_size() > 0)
         {
+            F internal_loop = loop;
             for (size_t i = 0; i < blks.get_num_blocks(); ++i)
-                push_task(std::forward<F>(loop), blks.start(i), blks.end(i));
+                push_task(std::forward<F>(internal_loop), blks.start(i), blks.end(i));
         }
     }
```

**System information**

* CPU model, architecture, # of cores and threads: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz 8 cores, 16 threads
* Operating system: Debian
* Name and version of C++ compiler: Debian clang version 14.0.6-2
* Full command used for compiling, including all compiler flags: clang++ -o test test.cpp
* Thread pool library version: 3.3

**Comment by bshoshany** [comment]
Thanks for the bug report! That's an interesting observation.

But if what you're saying is true, then in your suggested resolution, won't `internal_loop` be moved more than once as well? Or, if it's not moved, then won't this cause errors when `internal_loop` goes out of scope?

I think to truly resolve the issue, a separate copy of `loop` would need to be created for each block, but that would decrease performance due to multiple copying.

Since this actually works without issue in every single compiler and OS I've tested on, I'm inclined to just leave the forwarding as is. It seems that the major compilers automatically know how to deal with this particular forwarding situation.

Please let me know what you think.

**Comment by sethhillbrand** [comment]
That's fair.  You are correct that I needed to move `internal_loop` into the `for` block.

I suspect that your inclination is correct.  I do wonder, however, if the compiler would optimize away the copy.  I'll let you know once I have some results from my hunch.

**Comment by bshoshany** [comment]
Sounds good, let me know.
