### ISSUE TITLE
[BUG] unadorned std::scoped_lock gives a warning

### ISSUE THREAD

**Issue by grattle** [bshoshany/thread-pool#89]
using c++20 with clang 14 on linux, I get the following warning:
error: 'scoped_lock' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]

simply fixed by converting all std::scoped_lock  ->  std::scoped_lock<std::mutex>. This avoids using -W flags with clang 14. 

This was the only feature that wouldn't compile cleanly on c++20. I understand your minimal language is c++17, but this is a simple fix to allow newer language levels as well.

I love your simple yet elegant code, well done!

Arthur

**Comment by bshoshany** [comment]
Thanks for the bug report! However, I cannot reproduce this. I compiled with Clang 14.0.0 on Ubuntu 22.04.1 LTS with the flags `-std=c++20 -O3 -Wall -Wextra -Wconversion -Wsign-conversion -Wpedantic -Weffc++ -Wshadow -pthread` and did not see this warning. Which warning flags are you using? And which Linux distribution?

**Comment by grattle** [comment]
I'm on Debian testing distribution, using clang version 14.0.6-2. 

Removing all flags solves the problem. I seem to have accumulated many flags over the years. Not obvious to me which one causes the problem. Time to prune. I'll fiddle with my flags to see which one causes this problem. 

FYI the command line I used with results:

/usr/bin/clang++-14 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -I/home/artg/alocal/ajg_stuff/build-debug -I/usr/local/NuDB/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -march=native -pipe -Wall -Werror -Wshadow -Wno-c++98-compat -Weverything  -Wno-conversion -Wno-sign-compare -Wno-c++98-compat-pedantic -Wno-padded -Wno-zero-as-null-pointer-constant -g -fPIC -std=c++20 -MD -MT CMakeFiles/test_ajg_stuff.dir/task_queue.cpp.o -MF CMakeFiles/test_ajg_stuff.dir/task_queue.cpp.o.d -o CMakeFiles/test_ajg_stuff.dir/task_queue.cpp.o -c /home/artg/alocal/ajg_stuff/task_queue.cpp
In file included from /home/artg/alocal/ajg_stuff/task_queue.cpp:36:
In file included from /home/artg/alocal/ajg_stuff/task_queue.h:9:
/home/artg/alocal/ajg_stuff/BS_thread_pool.hpp:460:19: error: 'scoped_lock' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
            const std::scoped_lock tasks_lock(tasks_mutex);
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/mutex:692:11: note: add a deduction guide to suppress this warning
    class scoped_lock
          ^

**Comment by bshoshany** [comment]
Thanks for the information! If I recall correctly, the recommendation is that `-Weverything` should never be used for actual programs, it only exists for the Clang developers to test Clang itself (or something like that). That said, since the `-Wctad-maybe-unsupported` warning can be avoided by simply adding the template type explicitly instead of letting it be deduced automatically, and it's potentially a more "correct" way to do things, I will consider changing this in the next release. Thanks again :)

**Comment by bshoshany** [comment]
Update: Sorry it took me so long to address this issue. After some thought, I have decided not to make any changes. The thing is, `-Wctad-maybe-unsupported` complains about the locks (`std::scoped_lock` and `std::unique_lock`) not having any explicitly written class template argument deduction (CTAD) guides for the type of the mutex. However, since I always create these locks with a specific mutex passed as an argument to the constructor, e.g. `std::unique_lock tasks_lock(tasks_mutex)`, it is obvious that the template argument must be the type of `tasks_mutex`, which is `std::mutex`. I do not see any reason to specify that argument explicitly, as it makes the code less elegant and less readable, and no compiler in the world will have any issue deducing the correct template argument on its own.
