### ISSUE TITLE
[REQ] A way to figure out which thread current task is running on.

### ISSUE THREAD

**Issue by YoungXiang** [bshoshany/thread-pool#92]
So I need to Use this with freetype, and I need to create 1 freeType library for each thread, when executing tasks, i need to know which thread, current task is running, so that I can accquire the correct freeType library.

```cpp
auto task = [](unsigned int thread_id, ...) {}
pool.push_task(task, ...);
```

**Comment by alugowski** [comment]
[std::this_thread::get_id()](https://cplusplus.com/reference/thread/this_thread/get_id/) does that.

**Comment by bshoshany** [comment]
Hi @YoungXiang, thanks for opening this issue. Sorry it took me so long to reply. I'm currently on hiatus from developing this package, since I'm too busy teaching. However, I plan to release a new version in the summer.

As @alugowski says, you can use [`std::this_thread::get_id`](https://en.cppreference.com/w/cpp/thread/get_id) to get a unique identifier for the thread that the current task is running on. Hope this solves your issue!

**Comment by YoungXiang** [comment]
Thanks! I think I was looking for the thread index in the thread pool, not the identifier. 
It's just easier to use the index to locate the corresponding freetype context in my case. But thank you for the reply!

**Comment by bshoshany** [comment]
I think [`thread_local`](https://en.cppreference.com/w/c/thread/thread_local) can help you achieve what you want to do.

**Comment by bshoshany** [comment]
I think [`thread_local`](https://en.cppreference.com/w/cpp/keyword/thread_local) can help you achieve what you want to do.
