### ISSUE TITLE
[REQ] Execute Task with Schedule

### ISSUE THREAD

**Issue by orochi663** [bshoshany/thread-pool#97]
**Execution of a task that is enqueued at specific a time**

It would be a really nice to have if we can have a scheduled execution of task at a specific time. The task that are enqueued with time will be able to get executed at that time and not before than that. Something like: 

::push_hourly_task(repeat=-1 or N times);
::push_daily_task(repeat=-1 or N times);
etc.

**Comment by bshoshany** [comment]
Hi @orochi663, thanks for opening this issue. Sorry it took me so long to reply. I'm currently on hiatus from developing this package, since I'm too busy teaching. However, I plan to release a new version in the summer.

This is an interesting suggestion, but I feel that it is a specific **application** of the thread pool, i.e. something you would use the thread pool to implement in your own program, rather than a feature that the thread pool itself needs to have. So I feel that it is beyond the scope of this package.

Thanks again for the suggestion!
